### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by AP2020C** [fkaag71/dokuwiki-strata#3]
I tried to follow the tutorial at https://www.dokuwiki.org/plugin:strata:examples
Apart from the fact that it is not clear to me how the table can figure out where to read the data, after creating the 3 example pages, when in a page I enter

<table>
fields {
    -- Each field becomes a column in the displayed table
    ?name: Name
    ?pop: Population
}
-- The result set will contain one row for each city data object found by the query 
-- The first column contains a link to the page on which that data object code is found
?name is a: city
?name Population: ?pop
</table>

I get
Warning: count(): Parameter must be an array or an object that implements Countable in ...\dokuwiki\lib\plugins\strata\syntax\select.php on line 93
Warning: count(): Parameter must be an array or an object that implements Countable in ...\dokuwiki\lib\plugins\strata\syntax\select.php on line 98

And I only see Madrid

**Comment by fkaag71** [comment]
You are right. I never use this syntax, but rather 

<table ?name "Name" ?pop "Population>
?name is a: city
?name Population: ?pop
</table>

I will check, this is probably again a PHP8 impact.

**Comment by AP2020C** [comment]
I use Dokuwiki on a stick, not sure which version of php it is.
Can you post a full table-to-table snippet? I still get the same error.

**Comment by fkaag71** [comment]
I just published a fix that worked on my side. Please check.

**Comment by AP2020C** [comment]
Thanks for the update, I am now no longer receiving errors.
However...
the table only shows me Madrid.
Although I created the 3 pages, all under playground, to experiment.

dokuwiki\data\pages\playground>tree /f
C:.
│   playground.txt
│
└───data
...    └───cities
  ......          berlin.txt
      ......      london.txt
          ......  madrid.txt
isn't there a command for fixed spacing?

The column names confuse me: I cannot understand, for example, "name" if it refers to the column name or intermediate values. Fortunately, the reference table has a different name.
Can you create an example with more explicit names such as:
city_name_in_the_source_page
city_variable_intermediate
city_column_name_table_being_displayed
and others in case there are any.

**Comment by fkaag71** [comment]
Did you create the pages by editing each of them or by copying the files ? The database for Strata is only fed when you visit the page. For example, when I change pages with BatchEdit, I have to revisit all of them to get them again into the tables.

You should also take care to include the \~~NOCACHE~~directive in your page, otherwise it will not be updated.

The variables prefixed with ? can take any kind of name, they are not related to the data fields. The queries style is largely inspired by SPARQL.

**Comment by fkaag71** [comment]
I have reproduced the demo pages at https://cardynal.fr/smsi-demo/doku.php?id=data:cities, it did work without any issue.
