### ISSUE TITLE
Using type ref::namespace does not add namespace to the link

### ISSUE THREAD

**Issue by dimonic** [fkaag71/dokuwiki-strata#4]
I am using the strata plugin, with a table to show my items. I want to see a link in the table, but with Capitalised/spaced text like I have in a name field. This is what I am trying:
```
<table>
fields {
  ?n [ref::trains]: Name
  ?d: Description
  ?p: Price
}
?loco is a: asset
?loco Full Name: ?n
?loco Description: ?d
?loco Price: ?p
</table>
```
However, the link produced by ?n does not link to namespace trains as I would expect. I know I could just use ?loco, but that produces a lower cased _ replaced sentence that looks ugly, and it looks from the docs that the namespace syntax is exactly what I want. What gives?

**Comment by fkaag71** [comment]
Looking at the code, it clearly does not take into account the hint as a namespace.
I will try to fix this, but as a workaround you could consider the useHeading option in the general configuration of your wiki.

**Comment by fkaag71** [comment]
I have pushed a version that should fix the issue. Let me know.
Yet the useHeading solution could be more elegant, if you use consistently headings in your pages.

**Comment by dimonic** [comment]
Sorry, ignorant user here - do I just re-install, or do I need to git clone and copy?

**Comment by dimonic** [comment]
NM, just reinstalled, it works! Thankss very much. Now to try your other suggestion - but it's always good to have the feature match the docs!
